// filmes.js

export const filmes = [
    {
        id: "interestelar",
        titulo: "Interestelar",
        imagem: "Imagens/Interstellar_Filme.png",
        descricao: "Um grupo de astronautas viaja através de um buraco de minhoca em busca de um novo lar para a humanidade.",
        trailer: "i6avfCqKcQo",
        duracao: "2h 20 min",
        genero: "Ficção científica",
        classificacao: "+10 anos",
    },
    {
        id: "batman",
        titulo: "Batman",
        imagem: "Imagens/batman.jpg",
        descricao: "O herói de Gotham enfrenta novos desafios.",
        trailer: "zqfz04yCTnE",
        duracao: "1h 30 min",
        genero: "Suspense",
        classificacao: "+16",
    },
    {
        id: "godzilla-2-rei-dos-monstros",
        titulo: "Godzilla 2: Rei dos Monstros",
        imagem: "Imagens/godzilla2.jpg",
        descricao: "O rei encontra uma nova ameaça em seu reino.",
        trailer: "Cve9ouQp0tE",
        duracao: "2h 11 min",
        genero: "Ficção Científica",
        classificacao: "+12",
    },
    {
        id: "shin-godzilla",
        titulo: "Shin Godzilla",
        imagem: "Imagens/shingodzilla.jpg",
        descricao: "A humanidade se depara com a encarnação da destruição.",
        trailer: "eNox1a18qqw",
        duracao: "1h 59 min",
        genero: "Ficção Científica",
        classificacao: "+12",
    },
    {
        id: "michael",
        titulo: "Michael",
        imagem: "Imagens/michael.jpg",
        descricao: "A história do grande rei do pop Michael Jackson.",
        trailer: "14YXeHKOBUY",
        duracao: "2h 7 min",
        genero: "Musical/Drama Musical",
        classificacao: "+12",
    },
    {
        id: "homem-aranha-um-novo-dia",
        titulo: "Homem-Aranha: Um Novo Dia",
        imagem: "Imagens/homemaranha.jpg",
        descricao: "O grande herói enfrenta novas ameaças e encara as mudanças na sua vida.",
        trailer: "ZHMY6nvZAqs",
        duracao: "2h 30 min",
        genero: "Ação/Aventura",
        classificacao: "+12",
    },
    {
        id: "efeito-borboleta",
        titulo: "Efeito Borboleta",
        imagem: "Imagens/efeitoborboleta.jpg",
        descricao: "suspense psicológico e ficção científica que acompanha Evan Treborn, um jovem atormentado por graves lapsos de memória e traumas de infância.",
        trailer: "Zn9FvJA4l5Q",
        duracao: "2h",
        genero: "Terror/Ficção científica",
        classificacao: "+16",
    },
    {
        id: "togo",
        titulo: "Togo",
        imagem: "Imagens/togo.jpg",
        descricao: "conta a história real da Corrida do Soro de 1925 no Alasca, focando no treinador Leonhard Seppala e seu cão líder de trenó, Togo, que transportaram soro antidiftérico sob condições climáticas extremas.",
        trailer: "HMfyueM-ZBQ",
        duracao: "1h 54 min",
        genero: "Aventura/Drama",
        classificacao: "+10",
    },
    {
        id: "ctsd",
        titulo: "Como Treinar o Seu Dragão",
        imagem: "Imagens/ctsd.jpg",
        descricao: "conta a história de Soluço, um jovem viking franzino que muda a relação entre sua vila e os dragões.",
        trailer: "uv1V9BOb2M8",
        duracao: "1h 38 min",
        genero: "Infantil/Aventura",
        classificacao: "Livre",
    },
    {
        id: "killbill",
        titulo: "Kill Bill",
        imagem: "Imagens/killbill.jpg",
        descricao: "A Noiva (Beatrix Kiddo) acorda de um coma de quatro anos após ser traída e baleada no dia do seu casamento pelo seu ex-amante e chefe, Bill.",
        trailer: "Wv3kZxK9dwA",
        duracao: "1h 51 min",
        genero: "Ação/Terror",
        classificacao: "+18",
    },
    {
        id: "clubedaluta",
        titulo: "Clube da Luta",
        imagem: "Imagens/clubedaluta.jpg",
        descricao: "Jack é um executivo entediado e com insônia que muda sua rotina ao entrar em um clube de lutas secreto.",
        trailer: "qtRKdVHc-cE",
        duracao: "2h 19 min",
        genero: "Ação",
        classificacao: "+18",
    },
    {
        id: "jw2",
        titulo: "Jurassic World: Reino Ameaçado",
        imagem: "Imagens/jw2.jpg",
        descricao: "Acompanha Owen e Claire em uma missão de resgate na Ilha Nublar após uma ameaça vulcânica",
        trailer: "u2WuN96DSkY",
        duracao: "2h 9 min",
        genero: "Ação/Ficção científica",
        classificacao: "+12",
    },
    {
        id: "toystory3",
        titulo: "Toy Story 3",
        imagem: "Imagens/toystory3.jpg",
        descricao: "Andy tem 17 anos e está prestes a ir para a faculdade, precisando decidir o destino de seus antigos brinquedos.",
        trailer: "2BlMNH1QTeE",
        duracao: "1h 43 min",
        genero: "Infantil/Aventura",
        classificacao: "Livre",
    },
    {
        id: "hf3",
        titulo: "Homem de Ferro 3",
        imagem: "Imagens/homemdeferro3.jpg",
        descricao: "Tony Stark enfrentando um inimigo implacável que destrói seu mundo pessoal",
        trailer: "s7MHXDEdjS0",
        duracao: "2h 10 min",
        genero: "Ação/Fição científica",
        classificacao: "+12",
    },
    {
        id: "benjamin-button",
        titulo: "O Curioso Caso de Benjamin Button",
        imagem: "Imagens/benjamimbutton.jpg",
        descricao: "Conta a história de um homem que nasce com a aparência de um idoso e rejuvenesce com o passar dos anos",
        trailer: "lqijVXvw7_E",
        duracao: "2h 46 min",
        genero: "Romance/Fantasia",
        classificacao: "+12",
    },
    {
        id: "elcamino",
        titulo: "El Camino: A Breaking Bad Film",
        imagem: "Imagens/elcamino.jpg",
        descricao: "Sequência e epílogo da série Breaking Bad.",
        trailer: "Su6Y4tZPIMQ",
        duracao: "2h 2 min",
        genero: "Terror",
        classificacao: "+16",
    },
    {
        id: "coringa2",
        titulo: "Coringa: Delírio a Dois",
        imagem: "Imagens/coringa2.jpg",
        descricao: "O comediante fracassado Arthur Fleck está internado no Hospital Estadual Arkham aguardando julgamento por seus crimes.",
        trailer: "sHG2sAi2R-s",
        duracao: "2h 18 min",
        genero: "Musical",
        classificacao: "+16",
    },
    {
        id: "minecraft",
        titulo: "Um Filme Minecraft",
        imagem: "Imagens/minecraft.jpg",
        descricao: "Comédia de aventura e fantasia de 2025 baseada no famoso jogo da Mojang Studios",
        trailer: "EVKYAAES6JQ",
        duracao: "1h 41 min",
        genero: "Aventura/Fantasia",
        classificacao: "+10",
    },
    {
        id: "fnaf2",
        titulo: "Five Nights at Freddy's 2",
        imagem: "Imagens/fnaf2.jpg",
        descricao: "A história se passa um ano após os eventos trágicos do primeiro filme, quando Abby tenta se reconectar com os animatrônicos e acaba despertando um novo mal.",
        trailer: "w8oP0T-7USo",
        duracao: "1h 44 min",
        genero: "Terror",
        classificacao: "+14",
    },
    {
        id: "eradogelo3",
        titulo: "A Era do Gelo 3",
        imagem: "Imagens/eradogelo.jpg",
        descricao: "Mostra a manada descobrindo um mundo subterrâneo habitado por dinossauros para resgatar a preguiça Sid.",
        trailer: "-NF99TtfFEs",
        duracao: "1h 43 min",
        genero: "Aventura/Comédia",
        classificacao: "Livre",
    },
    {
        id: "guerrainfinita",
        titulo: "Vingadores: Guerra Infinita",
        imagem: "Imagens/guerrainfinita.jpg",
        descricao: "detalha a jornada dos Vingadores e aliados enfrentando o déspota intergalático Thanos, que busca reunir as seis Joias do Infinito para impor sua vontade à realidade, deixando o destino da existência incerto",
        trailer: "4jGRyEa2jhE",
        duracao: "2h 29 min",
        genero: "Ação/Ficção científica",
        classificacao: "+12",
    },
    {
        id: "toe",
        titulo: "The End of Evangelion",
        imagem: "Imagens/toe.jpg",
        descricao: "Dirigido por Hideaki Anno que serve como um final alternativo e complementar para a série de televisão Neon Genesis Evangelion.",
        trailer: "v1pWyWIu8x4",
        duracao: "1h 27 min",
        genero: "Ficção científica/Ação",
        classificacao: "+16",
    }
];

export const series = [
    {
        id: "stranger-things",
        titulo: "Stranger Things",
        imagem: "Imagens/Strangerthings_serie.jpg",
        descricao: "Um grupo de crianças enfrenta forças sobrenaturais.",
        trailer: "Wb3kaP580kA",
        duracao: "5 temporadas",
        genero: "Terror",
        classificacao: "+16",
    },
    {
        id: "dark",
        titulo: "Dark",
        imagem: "Imagens/dark.jpg",
        descricao: "Mistérios envolvendo viagens no tempo.",
        trailer: "JCCssUOtn2E",
        duracao: "3 temporadas",
        genero: "Terror",
        classificacao: "+16",
    },
    {
        id: "cobra-kai",
        titulo: "Cobra Kai",
        imagem: "Imagens/cobrakai.jpg",
        descricao: "Um ex-campão degenerado de karatê decide começar sua redenção em vida e ensina karatê para uma nova geração.",
        trailer: "dRtrKQa_mms",
        duracao: "6 temporadas",
        genero: "Ação",
        classificacao: "+14",
    },
    {
        id: "breaking-bad",
        titulo: "Breaking Bad",
        imagem: "Imagens/breakingbad.jpg",
        descricao: "Um professor de química com câncer pulmonar decide viver do contrabando de drogas para ganhar dinheiro.",
        trailer: "2gTC4uWP3_Y",
        duracao: "5 temporadas",
        genero: "Drama",
        classificacao: "+16",
    },
    {
        id: "bleach",
        titulo: "Bleach",
        imagem: "Imagens/bleach.jpg",
        descricao: "Um adolescente que consegue ver espiritos se torna um ceifador de almas e luta contra vários inimigos que querem destruir o mundo.",
        trailer: "ASobpXYYoVQ",
        duracao: "20 temporadas",
        genero: "Ação",
        classificacao: "+12",
    },
    {
        id: "neon-genesis-evangelion",
        titulo: "Neon Genesis Evangelion",
        imagem: "Imagens/nge.jpg",
        descricao: "Shinji Ikari decide ir visitar seu pai e luta contra anjos para impedir o Terceiro Impacto.",
        trailer: "13nSISwxrY4",
        duracao: "1 temporada",
        genero: "Ficção Científica",
        classificacao: "+14",
    },
    {
        id: "jjk",
        titulo: "Jujutsu Kaisen",
        imagem: "Imagens/jjk.jpg",
        descricao: "Acompanha a história de Yuji Itadori, um estudante do ensino médio com uma força física impressionante que vê sua vida mudar drasticamente após se envolver com um objeto amaldiçoado",
        trailer: "HGCsAcFzaFw",
        duracao: "3 temporadas",
        genero: "Ação/Fantasia",
        classificacao: "+16",
    },
    {
        id: "jojo",
        titulo: "Jojo no Kimyou na Bouken",
        imagem: "Imagens/jojo.jpg",
        descricao: "Acompanha as gerações da família Joestar em uma luta de um século contra forças sobrenaturais e o vilão Dio Brando",
        trailer: "43qoWFJbWF0",
        duracao: "7 temporadas",
        genero: "Ação/Fantasia",
        classificacao: "+16",
    },
    {
        id: "tokyoghoul",
        titulo: "Tokyo Ghoul",
        imagem: "Imagens/tokyoghoul.jpg",
        descricao: "Acompanha o estudante Ken Kaneki, que sobrevive a um encontro mortal com um ghoul (criatura que se alimenta de carne humana) e se transforma em um meio-ghoul",
        trailer: "7aMOurgDB-o",
        duracao: "2 temporadas",
        genero: "Fantasia/Suspense",
        classificacao: "+16",
    },
    {
        id: "nana",
        titulo: "Nana",
        imagem: "Imagens/nana.jpg",
        descricao: "Conta a história de duas jovens de 20 anos com o mesmo nome que se conhecem em um trem rumo a Tóquio e acabam dividindo um apartamento.",
        trailer: "Tad-n4Xh3nI",
        duracao: "1 temporada",
        genero: "Romance/Drama",
        classificacao: "+14",
    },
    {
        id: "haikyuu",
        titulo: "Haikyuu!!",
        imagem: "Imagens/haikyuu.jpg",
        descricao: "Acompanha a trajetória de Shoyo Hinata, um estudante fã de vôlei que entra para o Colégio Karasuno e precisa unir forças com seu antigo rival, Tobio Kageyama, para levar o time escolar ao topo do campeonato nacional.",
        trailer: "uEeZdVYu7AA",
        duracao: "4 temporadas",
        genero: "Esporte",
        classificacao: "+10",
    },
    {
        id: "blackmirror",
        titulo: "Black Mirror",
        imagem: "Imagens/blackmirror.jpg",
        descricao: "Black Mirror é uma série britânica de antologia e ficção científica criada por Charlie Brooker que explora o lado sombrio e os perigos da tecnologia moderna sobre o comportamento humano.",
        trailer: "M8qG0vS2zWM",
        duracao: "7 temporadas",
        genero: "Ficção científica",
        classificacao: "+16",
    },
    {
        id: "dexter",
        titulo: "Dexter",
        imagem: "Imagens/dexter.jpg",
        descricao: "Dexter Morgan é um analista forense de manchas de sangue de dia e um serial killer que caça outros assassinos à noite",
        trailer: "YQeUmSD1c3g",
        duracao: "8 temporadas",
        genero: "Drama",
        classificacao: "+16",
    },
    {
        id: "saul",
        titulo: "Better Call Saul",
        imagem: "Imagens/saul.jpg",
        descricao: "Better Call Saul acompanha a transformação de Jimmy McGill, um advogado de pequenas causas cheio de falhas, no infame e antiético Saul Goodman",
        trailer: "HN4oydykJFc",
        duracao: "6 temporadas",
        genero: "Drama",
        classificacao: "+16",
    },
    {
        id: "onepiece",
        titulo: "One Piece",
        imagem: "Imagens/onepiece.jpg",
        descricao: "One Piece acompanha as aventuras de Monkey D. Luffy, um jovem que ganha o corpo de borracha após comer uma Fruta do Diabo e sonha em se tornar o Rei dos Piratas",
        trailer: "rB13j38BtK0",
        duracao: "2 temporadas",
        genero: "Ação/Fantasia",
        classificacao: "+12",
    },
    {
        id: "gurrenlagann",
        titulo: "Tengen Toppa Gurren-Lagann",
        imagem: "Imagens/gurrenlagann.jpg",
        descricao: "Tengen Toppa Gurren Lagann se passa num futuro pós-apocalíptico onde a humanidade vive em vilas subterrâneas. Simon, um jovem escavador, e seu ousado amigo Kamina encontram uma chave em forma de broca e o rosto de um robô gigante. Junto com Yoko, eles fogem para a superfície e lutam contra opressores para reconquistar o destino do mundo.",
        trailer: "yMYEyoTRSbE",
        duracao: "1 temporada",
        genero: "Fantasia/Aventura",
        classificacao: "+12",
    },
    {
        id: "shameless",
        titulo: "Shameless",
        imagem: "Imagens/shameless.jpg",
        descricao: "A série Shameless acompanha a rotina caótica e disfuncional da família Gallagher em um bairro pobre de Chicago",
        trailer: "bBd9r2ZdX30",
        duracao: "11 temporadas",
        genero: "Drama/Comédia",
        classificacao: "+18",
    },
    {
        id: "cowboybebop",
        titulo: "Cowboy Bebop",
        imagem: "Imagens/cowboybebop.jpg",
        descricao: "Cowboy Bebop se passa no ano de 2071 e acompanha a tripulação da nave interplanetária Bebop, um grupo de caçadores de recompensas que viaja pelo sistema solar em busca de criminosos para pagar suas contas.",
        trailer: "OhNwckCLzis",
        duracao: "1 temporada",
        genero: "Drama/Ação",
        classificacao: "+14",
    },
    {
        id: "rickandmorty",
        titulo: "Rick and Morty",
        imagem: "Imagens/rickandmorty.jpg",
        descricao: "Rick and Morty é uma série animada de comédia e ficção científica que acompanha as viagens interdimensionais e caóticas do cientista genial e alcoólatra Rick Sanchez e seu neto adolescente Morty Smith.",
        trailer: "8zJmv_XQT70",
        duracao: "9 temporadas",
        genero: "Ficção científica/Comédia",
        classificacao: "+16",
    },
    {
        id: "scissorseven",
        titulo: "Scissor Seven",
        imagem: "Imagens/scissorseven.jpg",
        descricao: "Scissor Seven acompanha um cabeleireiro amnésico e atrapalhado que tenta ganhar a vida como assassino de aluguel usando uma tesoura para pagar por um tratamento de recuperação de memória.",
        trailer: "t3kDaWEaUjY",
        duracao: "5 temporadas",
        genero: "Ação/Fantasia",
        classificacao: "+12",
    },
    {
        id: "deathnote",
        titulo: "Death Note",
        imagem: "Imagens/deathnote.jpg",
        descricao: "Death Note acompanha Light Yagami, um estudante genial que encontra um caderno sobrenatural capaz de matar qualquer pessoa cujo nome seja escrito nele.",
        trailer: "NlJZ-YgAt-c",
        duracao: "1 temporada",
        genero: "Terror",
        classificacao: "+16",
    },
    {
        id: "wakfu",
        titulo: "Wakfu",
        imagem: "Imagens/wakfu.jpg",
        descricao: "Wakfu acompanha a jornada de Yugo, um garoto de 12 anos com poderes mágicos que descobre ser o último de sua espécie, os eliatropes.",
        trailer: "iCG24gBg764",
        duracao: "4 temporadas",
        genero: "Ação/Aventura",
        classificacao: "+14",
    }
];
